---
title: "Appendix of Statistical Inference Course Project - Part 2"
author: "Roshan Riazi"
output: pdf_document
---

##Codes

###Looking at head of ToothGrow data in step 1

```{r}
data(ToothGrowth)
ToothGrowth$dose <- as.factor(ToothGrowth$dose)
head(ToothGrowth)
```

###Code of first plot

```{r, fig.height=3}
library(ggplot2)
plot2 <- ggplot(ToothGrowth, aes(x = dose, y = len, fill = supp))
plot2 <- plot2 + geom_boxplot()
plot2 <- plot2 + labs(title = "Effect of Dose and Supplement on Length of Tooth", x = "Dose", y = "Length")
plot2
```

###Code of second plot

```{r, fig.height=3}
suppressMessages(library(gridExtra))
plot2.1 <- ggplot(ToothGrowth, aes(x = dose, y = len, fill = dose))
plot2.1 <- plot2.1 + geom_boxplot(aes(fill = dose))
plot2.1 <- plot2.1 + labs(x = "Dose", y = "Length")
plot2.2 <- ggplot(ToothGrowth, aes(x = supp, y = len, fill = supp))
plot2.2 <- plot2.2 + geom_boxplot(aes(fill = supp))
plot2.2 <- plot2.2 + labs(x = "Supplement", y = "Length")
grid.arrange(plot2.1, plot2.2, ncol = 2)
```

###Code of p-values of hypothesis tests for different dose groups

```{r}
suppressMessages(library(dplyr))
toothDose0.5 <- filter(ToothGrowth, dose == 0.5)
toothDose1 <- filter(ToothGrowth, dose == 1)
toothDose2 <- filter(ToothGrowth, dose == 2)
t1.1 <- t.test(toothDose0.5$len, toothDose1$len)
t1.2 <-t.test(toothDose0.5$len, toothDose2$len)
t1.3 <- t.test(toothDose1$len, toothDose2$len)
c("dose0.5-dose1" = t1.1$p.value, "dose0.5-dose2" = t1.2$p.value, "dose1-dose2" = t1.3$p.value)
```

###Complete results of hypothesis tests

```{r}
t1.1
t1.2
t1.3
t.test(len ~ supp, data = ToothGrowth)
```