---
title: "Appendix of Statistical Inference Course Project - Part 1"
author: "Roshan Riazi"
output: pdf_document
---

##Codes

###Code of plot 1

```{r, fig.height=3, results='hide'}
library(ggplot2)
plotData <- data.frame(mns)
plot1 <- ggplot(data = plotData, aes(x = mns))
plot1 <- plot1 + geom_histogram(aes(y = ..density..), fill = "blue", color = "black")
plot1 <- plot1 + geom_line(aes(x = c(simMean, simMean), y = c(0, .6),
                               col = "Simulation Mean"))
plot1 <- plot1 + geom_line(aes(x = c(theoMean, theoMean), y = c(0, .6),
                               col = "Theoretical Mean"))
plot1 <- plot1 + guides(col = guide_legend(title = NULL)) #removing legend title
plot1 <- plot1 + labs(title = "Distribution of Means of rexp")
plot1
```

###Code of plot 2

```{r, fig.height=3, results='hide'}
plot2 <- ggplot(data = plotData, aes(x = mns))
plot2 <- plot2 + geom_histogram(aes(y = ..density..), fill = "blue", color = "black")
plot2 <- plot2 + geom_line(aes(x = c(simMean+2*simSd, simMean+2*simSd), y = c(0, .6),
                               col = "Simulation sd"))
plot2 <- plot2 + geom_line(aes(x = c(simMean-2*simSd, simMean-2*simSd), y = c(0, .6),
                               col = "Simulation sd"))
plot2 <- plot2 + geom_line(aes(x = c(theoMean+2*theoSd, theoMean+2*theoSd), y = c(0, .6),
                               col = "Theoretical sd"))
plot2 <- plot2 + geom_line(aes(x = c(theoMean-2*theoSd, theoMean-2*theoSd), y = c(0, .6),
                               col = "Theoretical sd"))
plot2 <- plot2 + guides(col = guide_legend(title = NULL)) #removing legent title
plot2 <- plot2 + labs(title = "Distribution of Means of rexp")
plot2
```

###Code of plot 3

```{r, fig.height=3, results='hide'}
plot3 <- ggplot(plotData, aes(x = mns))
plot3 <- plot3 + geom_histogram(aes(y = ..density..), fill = "blue", color = "black")
plot3 <- plot3 + stat_function(fun = dnorm, args = list(mean = theoMean, sd = theoSd),
                               color = "red", size = 1)
plot3 <- plot3 + labs(title = "Distribution of Means of rexp")
plot3
```